# Generated by Django 3.1.1 on 2021-07-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
